pipeline {
  agent any
  stages {  
    stage('Maven Compile'){
        steps{
            echo 'Project compile stage'
            bat label: 'Compilation running', script: '''mvn compile'''
               }
    }
  
    
   
     stage('Jacoco Coverage Report') {
            steps{
                    jacoco()
        }
    }
      
    stage('SonarQube'){
        steps{
                bat label: '', script: '''mvn sonar:sonar \
                -Dsonar.host.url=http://localhost:9000 \
                -Dsonar.login=22eebb888d88b120829b708c0495b87acf7ed5ac'''
            }
           }  
            
      stage('Unit Test') {
       steps {
            echo 'Project Testing stage'
            bat label: 'Test running', script: '''mvn test'''
         
       }
       }  
  
  }
}